// Re-export Phosphor icons under the legacy names used across the codebase
export {
  ArrowRight as SendIcon,
  Columns as SplitIcon,
  ArrowsInLineHorizontal as MergeIcon,
  Plus as PlusIcon,
  Trash as TrashIcon,
  DownloadSimple as DownloadIcon,
  MagnifyingGlass as SearchIcon,
  Sparkle as SparkleIcon,
  ChartLineUp as ChartIcon,
  Stop as StopIcon,
  PencilSimple as PencilIcon,
  EyeSlash as EyeOffIcon,
  DotsSixVertical as GripIcon,
  Clipboard as ClipboardIcon,
  Check as CheckIcon,
  List as MenuIcon,
  X as XIcon,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRightIcon,
  CaretDown as ChevronDownIcon,
  // extra icons used in new UI
  Copy as CopyIcon,
  ArrowBendDownRight as ContinueIcon,
  ChatCircle as FollowUpIcon,
  Robot as AnalysisIcon,
  Scales as CompareIcon,
  Warning as CritiqueIcon,
  Checks as FactCheckIcon,
  Eye as EyeIcon,
  SlidersHorizontal as SliderIcon,
  Textbox as ContextIcon,
  PaperPlaneTilt as SendAltIcon,
  FlowArrow as CombineIcon,
  Star as StarIcon,
  ArrowCounterClockwise as RegenIcon,
} from "@phosphor-icons/react";
